# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f31e4061d070a72d4a562470622d0c0397448971ac24613554b5dbf568d43d6f7c878eacff5914994fedf559a821f94940557218d2c73fd4415aa5b2304258f

test:
  secret_key_base: 64cbf503c6da885d9c1a1172a170496721fc0f10def2a175055e6263ecff5646b1483e144cf4d21b1b7206d8c9fe1922804895f1a9b6e13305e15c28e8683f90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
